name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: pre-init file
        run: bash ./format_validate_all.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      # - name: Terraform Init
      #   id: init
      #   run: terraform init

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color
      
      # - name: Refresh Terraform State
      #   run: terraform refresh

      # - name: Terraform Apply
      #   run: terraform apply --auto-approve

      #   # id: apply
      #   # run: |
      #   #   set +e
      #   #   terraform apply -auto-approve
      #   #   APPLY_EXIT_CODE=$?
      #   #   if [ $APPLY_EXIT_CODE -ne 0 ]; then
      #   #     echo "Terraform apply failed. Retrying with now created app version..."
      #   #     terraform refresh
      #   #     terraform apply -auto-approve
      #   #   fi
      #   #   set -e

      # - name: Sleep for 1 minute
      #   run: sleep 60

      # - name: Terraform Destroy
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: terraform destroy -auto-approve
