name: "Terraform_prod"

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Approve the Terraform_prod'
        required: true

jobs:
  terraform_staging:
    name: "Terraform_prod"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      AWS_REGION: us-east-1

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

      #- name: Sleep for 10 minutes
      #  run: sleep 600

      #- name: Terraform Destroy
      #  run: terraform destroy -auto-approve