name: "Terraform_staging"

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  terraform_staging:
    name: "Terraform_staging"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      AWS_REGION: us-east-1

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: pre-init file
        run: bash ./format_validate_all.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=providers_staging.tfvars

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Refresh Terraform State
        run: terraform refresh

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Sleep for 1 minutes
        run: sleep 60

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Sleep for 2 minutes
        run: sleep 120